name = "huayun"
pages_build_output_dir = "dist"

compatibility_date = "2024-11-20"

[[d1_databases]]
binding = "DB"
database_name = "huayun_db"
database_id = "D220A23A-3578-4B36-97A6-e6B1A4bb2B4f"

[[kv_namespaces]]
binding = "SESSIONS"
id = "c8acac853b3348048e8F43ADF0E3caff"

[[r2_buckets]]
binding = "HUAYUN_BUCKET"
bucket_name = "huayun-images"
preview_bucket_name = "huayun-images"
